### ISSUE TITLE
Missing `file_transfer` event in cc-tweaked definitions

### ISSUE THREAD

**Issue by bananasov** [unicornpkg/cc-tweaked-ide-config#4]
Title says it all, types can be found in `library/types/events.lua`.

**Comment by tomodachi94** [comment]
This is an upstream bug. I'll open an issue on https://gitlab.com/carsakiller/cc-tweaked-documentation.

**Comment by tomodachi94** [comment]
Upstream report: https://gitlab.com/carsakiller/cc-tweaked-documentation/-/issues/47

**Comment by tomodachi94** [comment]
@Autist69420 would you be willing to transfer your fork of cc-tweaked-documentation onto the nvim-computercraft org? I'm not sure upstream is maintained.

**Comment by bananasov** [comment]
I am not sure how I would do that

**Comment by tomodachi94** [comment]
> I am not sure how I would do that

I would add you to the organization, grant you appropriate permissions, and you'd click the transfer button in the "Danger Zone" settings.

**Comment by bananasov** [comment]
> > I am not sure how I would do that
> 
> I would add you to the organization, grant you appropriate permissions, and you'd click the transfer button in the "Danger Zone" settings.

alright got it, I'll transfer it once you've invited me

**Comment by tomodachi94** [comment]
@Autist69420 You're in.

**Comment by bananasov** [comment]
Done.
